language: ruby
cache: bundler
script: bundle exec middleman build
deploy:
  provider: cloudfoundry
  api: https://api.cloud.service.gov.uk
  username: ida-operations+paas-build-bot@digital.cabinet-office.gov.uk
  password:
    secure: wapKwUZGD860WvfgUnSuKEJRKoB99MDklxGnPTWJIIPcwaRPlJaqwhMJvhO+cFRZRtPtFAGayxuQ9/XU6G/UQnU6G1s6O98hHjde03V47PgJkVSw/LXa/yMA9gC5vmvUuF/3vbNwisxyhmbbtkEESSGsbyiPEPN2LCxw5/y0fgB/YYSnw88SZ8OdA9+7s1MBz1pd/AuYwaCoxumRkTC6myKF9NWCwVcDws3FuIyrJVIQuF8Sk5pThQTgFSFb8B82ZRUXKmrZoIj7CmRHECtNkC9N5JjzLqq3Yub0ZvCxHugNoOm5JL4kYRXk37g48QIKX3DPRMv8aIV/JnNAE6PTlxoyzubJxiQe7/B4uBJtKJ2iipylUtzVJmrazMarVhvNHc4LFa2Mfcn5AD0Qcux5OY/MVGjjT7cDLt3XcTeps/K+4hJmO6+LV0Swi8dr2JwYlnE8RBXetyo2Y/snn56oN6R/ql1xMzZ7OjytTyCvXezC6/a15XHaeDsyeaMuU5cfFmZn5SXfX3WZBhT4N0ItPVM5F98zYuads9s7ykEBVRvFwNroW31eTnLJgROTi9B9aMaWQ0xLHwvHR4g9aegs0f5gqFgDkpjpeMdL6s3fjJa5zH/fPHclSzqOOgF5cTRTiwsru8ijqoIJ6isgRScZszZ7W9iR8Cl14EK3MDV03DI=
  organization: govuk-verify
  space: docs
  on:
    repo: alphagov/verify-idp-guidance
